// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package find

import (
	"context"

	"github.com/loft-sh/log"
	"github.com/loft-sh/vcluster/pkg/cli/find"
	mock "github.com/stretchr/testify/mock"
)

// NewMockVClusterLister creates a new instance of MockVClusterLister. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockVClusterLister(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockVClusterLister {
	mock := &MockVClusterLister{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockVClusterLister is an autogenerated mock type for the VClusterLister type
type MockVClusterLister struct {
	mock.Mock
}

type MockVClusterLister_Expecter struct {
	mock *mock.Mock
}

func (_m *MockVClusterLister) EXPECT() *MockVClusterLister_Expecter {
	return &MockVClusterLister_Expecter{mock: &_m.Mock}
}

// List provides a mock function for the type MockVClusterLister
func (_mock *MockVClusterLister) List(ctx context.Context, currentContext string, name string, namespace string, logger log.Logger) ([]find.VCluster, error) {
	ret := _mock.Called(ctx, currentContext, name, namespace, logger)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []find.VCluster
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, log.Logger) ([]find.VCluster, error)); ok {
		return returnFunc(ctx, currentContext, name, namespace, logger)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, log.Logger) []find.VCluster); ok {
		r0 = returnFunc(ctx, currentContext, name, namespace, logger)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]find.VCluster)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string, log.Logger) error); ok {
		r1 = returnFunc(ctx, currentContext, name, namespace, logger)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVClusterLister_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockVClusterLister_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - currentContext string
//   - name string
//   - namespace string
//   - logger log.Logger
func (_e *MockVClusterLister_Expecter) List(ctx interface{}, currentContext interface{}, name interface{}, namespace interface{}, logger interface{}) *MockVClusterLister_List_Call {
	return &MockVClusterLister_List_Call{Call: _e.mock.On("List", ctx, currentContext, name, namespace, logger)}
}

func (_c *MockVClusterLister_List_Call) Run(run func(ctx context.Context, currentContext string, name string, namespace string, logger log.Logger)) *MockVClusterLister_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 log.Logger
		if args[4] != nil {
			arg4 = args[4].(log.Logger)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockVClusterLister_List_Call) Return(vClusters []find.VCluster, err error) *MockVClusterLister_List_Call {
	_c.Call.Return(vClusters, err)
	return _c
}

func (_c *MockVClusterLister_List_Call) RunAndReturn(run func(ctx context.Context, currentContext string, name string, namespace string, logger log.Logger) ([]find.VCluster, error)) *MockVClusterLister_List_Call {
	_c.Call.Return(run)
	return _c
}
