// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package cli

import (
	"context"

	"github.com/loft-sh/vcluster/pkg/cli"
	mock "github.com/stretchr/testify/mock"
)

// NewMockDockerContainerLister creates a new instance of MockDockerContainerLister. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDockerContainerLister(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDockerContainerLister {
	mock := &MockDockerContainerLister{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDockerContainerLister is an autogenerated mock type for the DockerContainerLister type
type MockDockerContainerLister struct {
	mock.Mock
}

type MockDockerContainerLister_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDockerContainerLister) EXPECT() *MockDockerContainerLister_Expecter {
	return &MockDockerContainerLister_Expecter{mock: &_m.Mock}
}

// Find provides a mock function for the type MockDockerContainerLister
func (_mock *MockDockerContainerLister) Find(ctx context.Context, prefix string) ([]cli.DockerVCluster, error) {
	ret := _mock.Called(ctx, prefix)

	if len(ret) == 0 {
		panic("no return value specified for Find")
	}

	var r0 []cli.DockerVCluster
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]cli.DockerVCluster, error)); ok {
		return returnFunc(ctx, prefix)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []cli.DockerVCluster); ok {
		r0 = returnFunc(ctx, prefix)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]cli.DockerVCluster)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, prefix)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDockerContainerLister_Find_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Find'
type MockDockerContainerLister_Find_Call struct {
	*mock.Call
}

// Find is a helper method to define mock.On call
//   - ctx context.Context
//   - prefix string
func (_e *MockDockerContainerLister_Expecter) Find(ctx interface{}, prefix interface{}) *MockDockerContainerLister_Find_Call {
	return &MockDockerContainerLister_Find_Call{Call: _e.mock.On("Find", ctx, prefix)}
}

func (_c *MockDockerContainerLister_Find_Call) Run(run func(ctx context.Context, prefix string)) *MockDockerContainerLister_Find_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDockerContainerLister_Find_Call) Return(dockerVClusters []cli.DockerVCluster, err error) *MockDockerContainerLister_Find_Call {
	_c.Call.Return(dockerVClusters, err)
	return _c
}

func (_c *MockDockerContainerLister_Find_Call) RunAndReturn(run func(ctx context.Context, prefix string) ([]cli.DockerVCluster, error)) *MockDockerContainerLister_Find_Call {
	_c.Call.Return(run)
	return _c
}
