# Global configuration.
#
# Disable automatic mock generation. Only explicitly defined interfaces will be mocked.
all: false
# Use the testify template (since all the tests that use mocks use testify assertions).
template: testify
# Naming pattern for generated mock structs.
# Example: VClusterLister -> MockVClusterLister.
structname: "{{.Mock}}{{.InterfaceName}}"
# Package name used inside generated mock files.
# Example: Package `pkg/cli/find` -> Mock package name `find`.
pkgname: "{{.SrcPackageName}}"
# Only process explicitly listed packages (no subpackage recursion).
recursive: false

# Package-specific configuration.
packages:
  # Package `pkg/cli` configuration.
  github.com/loft-sh/vcluster/pkg/cli:
    config:
      # Mocks directory for current package: `pkg/mocks/cli/`
      # - `pkg/mocks/` - Common directory for all mocks in the /pkg/ directory.
      # - `cli/`       - Corresponds to the original package structure.
      dir: "{{.InterfaceDir}}/../mocks/cli"

    # Interface-specific configuration.
    interfaces:
      # Interface `DockerContainerLister` configuration.
      DockerContainerLister:
        config:
          # Output file name for this interface mock. This corresponds to the original file name.
          filename: cli.go

  # Package `pkg/cli/find` configuration.
  github.com/loft-sh/vcluster/pkg/cli/find:
    config:
      # Mocks directory for current package: `pkg/mocks/cli/find/`
      # - `pkg/mocks/` - Common directory for all mocks in the /pkg/ directory.
      # - `cli/find/`  - Corresponds to the original package structure.
      dir: "{{.InterfaceDir}}/../../mocks/cli/find"

    # Interface-specific configuration.
    interfaces:
      # Interface `VClusterLister` configuration.
      VClusterLister:
        config:
          # Output file name for this interface mock. This corresponds to the original file name.
          filename: find.go
      # Interface `VClusterGetter` configuration.
      VClusterGetter:
        config:
          # Output file name for this interface mock. This corresponds to the original file name.
          filename: find.go

  # Package `pkg/platform` configuration.
  github.com/loft-sh/vcluster/pkg/platform:
    config:
      # Mocks directory for current package: `pkg/mocks/platform/`
      # - `pkg/mocks/` - Common directory for all mocks in the /pkg/ directory.
      # - `platform/`  - Corresponds to the original package structure.
      dir: "{{.InterfaceDir}}/../mocks/platform"

    # Interface-specific configuration.
    interfaces:
      # Interface `PlatformLister` configuration.
      PlatformLister:
        config:
          # Output file name for this interface mock. This corresponds to the original file name.
          filename: helper.go
      # Interface `Client` configuration.
      Client:
        config:
          # Output file name for this interface mock. This corresponds to the original file name.
          filename: client.go

  # Package `pkg/platform/kube` configuration.
  github.com/loft-sh/vcluster/pkg/platform/kube:
    config:
      # Mocks directory for current package: `pkg/mocks/platform/kube/`
      # - `pkg/mocks/` - Common directory for all mocks in the /pkg/ directory.
      # - `platform/kube/`  - Corresponds to the original package structure.
      dir: "{{.InterfaceDir}}/../../mocks/platform/kube"

    # Interface-specific configuration.
    interfaces:
      # Interface `Interface` configuration.
      Interface:
        config:
          # Output file name for this interface mock. This corresponds to the original file name.
          filename: client.go

  # Package `pkg/helm` configuration.
  github.com/loft-sh/vcluster/pkg/helm:
    config:
      # Mocks directory for current package: `pkg/mocks/helm/`
      # - `pkg/mocks/` - Common directory for all mocks in the /pkg/ directory.
      # - `helm/`       - Corresponds to the original package structure.
      dir: "{{.InterfaceDir}}/../mocks/helm"
    # Interface-specific configuration.
    interfaces:
      # Interface `Client` configuration.
      Client:
        config:
          # Output file name for this interface mock. This corresponds to the original file name.
          filename: helm.go

  # Package `pkg/kube/clientset` configuration.
  github.com/loft-sh/vcluster/pkg/kube/clientset:
    config:
      # Mocks directory for current package: `pkg/mocks/kube/clientset/`
      # - `pkg/mocks/` - Common directory for all mocks in the /pkg/ directory.
      # - `kube/clientset/`       - Corresponds to the original package structure.
      dir: "{{.InterfaceDir}}/../../mocks/kube/clientset"

    # Interface-specific configuration.
    interfaces:
      # Interface `LoftClientSetInterface` configuration.
      LoftClientSetInterface:
        config:
          # Output file name for this interface mock. This corresponds to the original file name.
          filename: clientset.go

      # Interface `ManagementV1Interface` configuration.
      ManagementV1Interface:
        config:
          # Output file name for this interface mock. This corresponds to the original file name.
          filename: clientset.go

      # Interface `VirtualClusterInstanceInterface` configuration.
      VirtualClusterInstanceInterface:
        config:
          # Output file name for this interface mock. This corresponds to the original file name.
          filename: clientset.go

  # Package `pkg/cli/helmclientinit` configuration.
  github.com/loft-sh/vcluster/pkg/cli/helmclientinit:
    config:
      # Mocks directory for current package: `pkg/mocks/cli/helmclientinit/`
      # - `pkg/mocks/` - Common directory for all mocks in the /pkg/ directory.
      # - `cli/helmclientinit/`  - Corresponds to the original package structure.
      dir: "{{.InterfaceDir}}/../../mocks/cli/helmclientinit"
    # Interface-specific configuration.
    interfaces:
      # Interface `HelmClientInitializer` configuration.
      HelmClientInitializer:
        config:
          # Output file name for this interface mock. This corresponds to the original file name.
          filename: helm_client_initializer.go
