// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package helmclientinit

import (
	"github.com/loft-sh/vcluster/pkg/helm"
	mock "github.com/stretchr/testify/mock"
	"k8s.io/client-go/tools/clientcmd/api"
)

// NewMockHelmClientInitializer creates a new instance of MockHelmClientInitializer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHelmClientInitializer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHelmClientInitializer {
	mock := &MockHelmClientInitializer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockHelmClientInitializer is an autogenerated mock type for the HelmClientInitializer type
type MockHelmClientInitializer struct {
	mock.Mock
}

type MockHelmClientInitializer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHelmClientInitializer) EXPECT() *MockHelmClientInitializer_Expecter {
	return &MockHelmClientInitializer_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type MockHelmClientInitializer
func (_mock *MockHelmClientInitializer) Get(kubeConfig *api.Config) helm.Client {
	ret := _mock.Called(kubeConfig)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 helm.Client
	if returnFunc, ok := ret.Get(0).(func(*api.Config) helm.Client); ok {
		r0 = returnFunc(kubeConfig)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(helm.Client)
		}
	}
	return r0
}

// MockHelmClientInitializer_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockHelmClientInitializer_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - kubeConfig *api.Config
func (_e *MockHelmClientInitializer_Expecter) Get(kubeConfig interface{}) *MockHelmClientInitializer_Get_Call {
	return &MockHelmClientInitializer_Get_Call{Call: _e.mock.On("Get", kubeConfig)}
}

func (_c *MockHelmClientInitializer_Get_Call) Run(run func(kubeConfig *api.Config)) *MockHelmClientInitializer_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *api.Config
		if args[0] != nil {
			arg0 = args[0].(*api.Config)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockHelmClientInitializer_Get_Call) Return(client helm.Client) *MockHelmClientInitializer_Get_Call {
	_c.Call.Return(client)
	return _c
}

func (_c *MockHelmClientInitializer_Get_Call) RunAndReturn(run func(kubeConfig *api.Config) helm.Client) *MockHelmClientInitializer_Get_Call {
	_c.Call.Return(run)
	return _c
}
