// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package platform

import (
	"context"

	"github.com/loft-sh/api/v4/pkg/apis/management/v1"
	"github.com/loft-sh/api/v4/pkg/auth"
	"github.com/loft-sh/log"
	"github.com/loft-sh/vcluster/pkg/cli/config"
	"github.com/loft-sh/vcluster/pkg/platform/kube"
	mock "github.com/stretchr/testify/mock"
	"k8s.io/client-go/rest"
)

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// Cluster provides a mock function for the type MockClient
func (_mock *MockClient) Cluster(cluster string) (kube.Interface, error) {
	ret := _mock.Called(cluster)

	if len(ret) == 0 {
		panic("no return value specified for Cluster")
	}

	var r0 kube.Interface
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (kube.Interface, error)); ok {
		return returnFunc(cluster)
	}
	if returnFunc, ok := ret.Get(0).(func(string) kube.Interface); ok {
		r0 = returnFunc(cluster)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(kube.Interface)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(cluster)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_Cluster_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Cluster'
type MockClient_Cluster_Call struct {
	*mock.Call
}

// Cluster is a helper method to define mock.On call
//   - cluster string
func (_e *MockClient_Expecter) Cluster(cluster interface{}) *MockClient_Cluster_Call {
	return &MockClient_Cluster_Call{Call: _e.mock.On("Cluster", cluster)}
}

func (_c *MockClient_Cluster_Call) Run(run func(cluster string)) *MockClient_Cluster_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockClient_Cluster_Call) Return(interfaceParam kube.Interface, err error) *MockClient_Cluster_Call {
	_c.Call.Return(interfaceParam, err)
	return _c
}

func (_c *MockClient_Cluster_Call) RunAndReturn(run func(cluster string) (kube.Interface, error)) *MockClient_Cluster_Call {
	_c.Call.Return(run)
	return _c
}

// Config provides a mock function for the type MockClient
func (_mock *MockClient) Config() *config.CLI {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Config")
	}

	var r0 *config.CLI
	if returnFunc, ok := ret.Get(0).(func() *config.CLI); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*config.CLI)
		}
	}
	return r0
}

// MockClient_Config_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Config'
type MockClient_Config_Call struct {
	*mock.Call
}

// Config is a helper method to define mock.On call
func (_e *MockClient_Expecter) Config() *MockClient_Config_Call {
	return &MockClient_Config_Call{Call: _e.mock.On("Config")}
}

func (_c *MockClient_Config_Call) Run(run func()) *MockClient_Config_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClient_Config_Call) Return(cLI *config.CLI) *MockClient_Config_Call {
	_c.Call.Return(cLI)
	return _c
}

func (_c *MockClient_Config_Call) RunAndReturn(run func() *config.CLI) *MockClient_Config_Call {
	_c.Call.Return(run)
	return _c
}

// Login provides a mock function for the type MockClient
func (_mock *MockClient) Login(host string, insecure bool, log1 log.Logger) error {
	ret := _mock.Called(host, insecure, log1)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, bool, log.Logger) error); ok {
		r0 = returnFunc(host, insecure, log1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type MockClient_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - host string
//   - insecure bool
//   - log1 log.Logger
func (_e *MockClient_Expecter) Login(host interface{}, insecure interface{}, log1 interface{}) *MockClient_Login_Call {
	return &MockClient_Login_Call{Call: _e.mock.On("Login", host, insecure, log1)}
}

func (_c *MockClient_Login_Call) Run(run func(host string, insecure bool, log1 log.Logger)) *MockClient_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 bool
		if args[1] != nil {
			arg1 = args[1].(bool)
		}
		var arg2 log.Logger
		if args[2] != nil {
			arg2 = args[2].(log.Logger)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockClient_Login_Call) Return(err error) *MockClient_Login_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_Login_Call) RunAndReturn(run func(host string, insecure bool, log1 log.Logger) error) *MockClient_Login_Call {
	_c.Call.Return(run)
	return _c
}

// LoginWithAccessKey provides a mock function for the type MockClient
func (_mock *MockClient) LoginWithAccessKey(host string, accessKey string, insecure bool) error {
	ret := _mock.Called(host, accessKey, insecure)

	if len(ret) == 0 {
		panic("no return value specified for LoginWithAccessKey")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string, bool) error); ok {
		r0 = returnFunc(host, accessKey, insecure)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_LoginWithAccessKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoginWithAccessKey'
type MockClient_LoginWithAccessKey_Call struct {
	*mock.Call
}

// LoginWithAccessKey is a helper method to define mock.On call
//   - host string
//   - accessKey string
//   - insecure bool
func (_e *MockClient_Expecter) LoginWithAccessKey(host interface{}, accessKey interface{}, insecure interface{}) *MockClient_LoginWithAccessKey_Call {
	return &MockClient_LoginWithAccessKey_Call{Call: _e.mock.On("LoginWithAccessKey", host, accessKey, insecure)}
}

func (_c *MockClient_LoginWithAccessKey_Call) Run(run func(host string, accessKey string, insecure bool)) *MockClient_LoginWithAccessKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockClient_LoginWithAccessKey_Call) Return(err error) *MockClient_LoginWithAccessKey_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_LoginWithAccessKey_Call) RunAndReturn(run func(host string, accessKey string, insecure bool) error) *MockClient_LoginWithAccessKey_Call {
	_c.Call.Return(run)
	return _c
}

// Logout provides a mock function for the type MockClient
func (_mock *MockClient) Logout(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Logout")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_Logout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logout'
type MockClient_Logout_Call struct {
	*mock.Call
}

// Logout is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockClient_Expecter) Logout(ctx interface{}) *MockClient_Logout_Call {
	return &MockClient_Logout_Call{Call: _e.mock.On("Logout", ctx)}
}

func (_c *MockClient_Logout_Call) Run(run func(ctx context.Context)) *MockClient_Logout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockClient_Logout_Call) Return(err error) *MockClient_Logout_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_Logout_Call) RunAndReturn(run func(ctx context.Context) error) *MockClient_Logout_Call {
	_c.Call.Return(run)
	return _c
}

// Management provides a mock function for the type MockClient
func (_mock *MockClient) Management() (kube.Interface, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Management")
	}

	var r0 kube.Interface
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (kube.Interface, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() kube.Interface); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(kube.Interface)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_Management_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Management'
type MockClient_Management_Call struct {
	*mock.Call
}

// Management is a helper method to define mock.On call
func (_e *MockClient_Expecter) Management() *MockClient_Management_Call {
	return &MockClient_Management_Call{Call: _e.mock.On("Management")}
}

func (_c *MockClient_Management_Call) Run(run func()) *MockClient_Management_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClient_Management_Call) Return(interfaceParam kube.Interface, err error) *MockClient_Management_Call {
	_c.Call.Return(interfaceParam, err)
	return _c
}

func (_c *MockClient_Management_Call) RunAndReturn(run func() (kube.Interface, error)) *MockClient_Management_Call {
	_c.Call.Return(run)
	return _c
}

// ManagementConfig provides a mock function for the type MockClient
func (_mock *MockClient) ManagementConfig() (*rest.Config, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ManagementConfig")
	}

	var r0 *rest.Config
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (*rest.Config, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() *rest.Config); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rest.Config)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_ManagementConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ManagementConfig'
type MockClient_ManagementConfig_Call struct {
	*mock.Call
}

// ManagementConfig is a helper method to define mock.On call
func (_e *MockClient_Expecter) ManagementConfig() *MockClient_ManagementConfig_Call {
	return &MockClient_ManagementConfig_Call{Call: _e.mock.On("ManagementConfig")}
}

func (_c *MockClient_ManagementConfig_Call) Run(run func()) *MockClient_ManagementConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClient_ManagementConfig_Call) Return(config1 *rest.Config, err error) *MockClient_ManagementConfig_Call {
	_c.Call.Return(config1, err)
	return _c
}

func (_c *MockClient_ManagementConfig_Call) RunAndReturn(run func() (*rest.Config, error)) *MockClient_ManagementConfig_Call {
	_c.Call.Return(run)
	return _c
}

// RefreshSelf provides a mock function for the type MockClient
func (_mock *MockClient) RefreshSelf(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for RefreshSelf")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_RefreshSelf_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RefreshSelf'
type MockClient_RefreshSelf_Call struct {
	*mock.Call
}

// RefreshSelf is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockClient_Expecter) RefreshSelf(ctx interface{}) *MockClient_RefreshSelf_Call {
	return &MockClient_RefreshSelf_Call{Call: _e.mock.On("RefreshSelf", ctx)}
}

func (_c *MockClient_RefreshSelf_Call) Run(run func(ctx context.Context)) *MockClient_RefreshSelf_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockClient_RefreshSelf_Call) Return(err error) *MockClient_RefreshSelf_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_RefreshSelf_Call) RunAndReturn(run func(ctx context.Context) error) *MockClient_RefreshSelf_Call {
	_c.Call.Return(run)
	return _c
}

// RestConfig provides a mock function for the type MockClient
func (_mock *MockClient) RestConfig(hostSuffix string) (*rest.Config, error) {
	ret := _mock.Called(hostSuffix)

	if len(ret) == 0 {
		panic("no return value specified for RestConfig")
	}

	var r0 *rest.Config
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*rest.Config, error)); ok {
		return returnFunc(hostSuffix)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *rest.Config); ok {
		r0 = returnFunc(hostSuffix)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rest.Config)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(hostSuffix)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_RestConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RestConfig'
type MockClient_RestConfig_Call struct {
	*mock.Call
}

// RestConfig is a helper method to define mock.On call
//   - hostSuffix string
func (_e *MockClient_Expecter) RestConfig(hostSuffix interface{}) *MockClient_RestConfig_Call {
	return &MockClient_RestConfig_Call{Call: _e.mock.On("RestConfig", hostSuffix)}
}

func (_c *MockClient_RestConfig_Call) Run(run func(hostSuffix string)) *MockClient_RestConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockClient_RestConfig_Call) Return(config1 *rest.Config, err error) *MockClient_RestConfig_Call {
	_c.Call.Return(config1, err)
	return _c
}

func (_c *MockClient_RestConfig_Call) RunAndReturn(run func(hostSuffix string) (*rest.Config, error)) *MockClient_RestConfig_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockClient
func (_mock *MockClient) Save() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockClient_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
func (_e *MockClient_Expecter) Save() *MockClient_Save_Call {
	return &MockClient_Save_Call{Call: _e.mock.On("Save")}
}

func (_c *MockClient_Save_Call) Run(run func()) *MockClient_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClient_Save_Call) Return(err error) *MockClient_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_Save_Call) RunAndReturn(run func() error) *MockClient_Save_Call {
	_c.Call.Return(run)
	return _c
}

// Self provides a mock function for the type MockClient
func (_mock *MockClient) Self() *v1.Self {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Self")
	}

	var r0 *v1.Self
	if returnFunc, ok := ret.Get(0).(func() *v1.Self); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Self)
		}
	}
	return r0
}

// MockClient_Self_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Self'
type MockClient_Self_Call struct {
	*mock.Call
}

// Self is a helper method to define mock.On call
func (_e *MockClient_Expecter) Self() *MockClient_Self_Call {
	return &MockClient_Self_Call{Call: _e.mock.On("Self")}
}

func (_c *MockClient_Self_Call) Run(run func()) *MockClient_Self_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClient_Self_Call) Return(self *v1.Self) *MockClient_Self_Call {
	_c.Call.Return(self)
	return _c
}

func (_c *MockClient_Self_Call) RunAndReturn(run func() *v1.Self) *MockClient_Self_Call {
	_c.Call.Return(run)
	return _c
}

// Version provides a mock function for the type MockClient
func (_mock *MockClient) Version() (*auth.Version, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Version")
	}

	var r0 *auth.Version
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (*auth.Version, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() *auth.Version); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.Version)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_Version_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Version'
type MockClient_Version_Call struct {
	*mock.Call
}

// Version is a helper method to define mock.On call
func (_e *MockClient_Expecter) Version() *MockClient_Version_Call {
	return &MockClient_Version_Call{Call: _e.mock.On("Version")}
}

func (_c *MockClient_Version_Call) Run(run func()) *MockClient_Version_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClient_Version_Call) Return(version *auth.Version, err error) *MockClient_Version_Call {
	_c.Call.Return(version, err)
	return _c
}

func (_c *MockClient_Version_Call) RunAndReturn(run func() (*auth.Version, error)) *MockClient_Version_Call {
	_c.Call.Return(run)
	return _c
}

// VirtualCluster provides a mock function for the type MockClient
func (_mock *MockClient) VirtualCluster(cluster string, namespace string, virtualCluster string) (kube.Interface, error) {
	ret := _mock.Called(cluster, namespace, virtualCluster)

	if len(ret) == 0 {
		panic("no return value specified for VirtualCluster")
	}

	var r0 kube.Interface
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string, string) (kube.Interface, error)); ok {
		return returnFunc(cluster, namespace, virtualCluster)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string, string) kube.Interface); ok {
		r0 = returnFunc(cluster, namespace, virtualCluster)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(kube.Interface)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string, string) error); ok {
		r1 = returnFunc(cluster, namespace, virtualCluster)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_VirtualCluster_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VirtualCluster'
type MockClient_VirtualCluster_Call struct {
	*mock.Call
}

// VirtualCluster is a helper method to define mock.On call
//   - cluster string
//   - namespace string
//   - virtualCluster string
func (_e *MockClient_Expecter) VirtualCluster(cluster interface{}, namespace interface{}, virtualCluster interface{}) *MockClient_VirtualCluster_Call {
	return &MockClient_VirtualCluster_Call{Call: _e.mock.On("VirtualCluster", cluster, namespace, virtualCluster)}
}

func (_c *MockClient_VirtualCluster_Call) Run(run func(cluster string, namespace string, virtualCluster string)) *MockClient_VirtualCluster_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockClient_VirtualCluster_Call) Return(interfaceParam kube.Interface, err error) *MockClient_VirtualCluster_Call {
	_c.Call.Return(interfaceParam, err)
	return _c
}

func (_c *MockClient_VirtualCluster_Call) RunAndReturn(run func(cluster string, namespace string, virtualCluster string) (kube.Interface, error)) *MockClient_VirtualCluster_Call {
	_c.Call.Return(run)
	return _c
}
