// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package helm

import (
	"context"

	"github.com/loft-sh/vcluster/pkg/helm"
	mock "github.com/stretchr/testify/mock"
)

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type MockClient
func (_mock *MockClient) Delete(name string, namespace string) error {
	ret := _mock.Called(name, namespace)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = returnFunc(name, namespace)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockClient_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - name string
//   - namespace string
func (_e *MockClient_Expecter) Delete(name interface{}, namespace interface{}) *MockClient_Delete_Call {
	return &MockClient_Delete_Call{Call: _e.mock.On("Delete", name, namespace)}
}

func (_c *MockClient_Delete_Call) Run(run func(name string, namespace string)) *MockClient_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClient_Delete_Call) Return(err error) *MockClient_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_Delete_Call) RunAndReturn(run func(name string, namespace string) error) *MockClient_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Exists provides a mock function for the type MockClient
func (_mock *MockClient) Exists(name string, namespace string) (bool, error) {
	ret := _mock.Called(name, namespace)

	if len(ret) == 0 {
		panic("no return value specified for Exists")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) (bool, error)); ok {
		return returnFunc(name, namespace)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) bool); ok {
		r0 = returnFunc(name, namespace)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(name, namespace)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_Exists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exists'
type MockClient_Exists_Call struct {
	*mock.Call
}

// Exists is a helper method to define mock.On call
//   - name string
//   - namespace string
func (_e *MockClient_Expecter) Exists(name interface{}, namespace interface{}) *MockClient_Exists_Call {
	return &MockClient_Exists_Call{Call: _e.mock.On("Exists", name, namespace)}
}

func (_c *MockClient_Exists_Call) Run(run func(name string, namespace string)) *MockClient_Exists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClient_Exists_Call) Return(b bool, err error) *MockClient_Exists_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockClient_Exists_Call) RunAndReturn(run func(name string, namespace string) (bool, error)) *MockClient_Exists_Call {
	_c.Call.Return(run)
	return _c
}

// GetValues provides a mock function for the type MockClient
func (_mock *MockClient) GetValues(ctx context.Context, name string, namespace string, all bool) ([]byte, error) {
	ret := _mock.Called(ctx, name, namespace, all)

	if len(ret) == 0 {
		panic("no return value specified for GetValues")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, bool) ([]byte, error)); ok {
		return returnFunc(ctx, name, namespace, all)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, bool) []byte); ok {
		r0 = returnFunc(ctx, name, namespace, all)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, bool) error); ok {
		r1 = returnFunc(ctx, name, namespace, all)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_GetValues_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetValues'
type MockClient_GetValues_Call struct {
	*mock.Call
}

// GetValues is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - namespace string
//   - all bool
func (_e *MockClient_Expecter) GetValues(ctx interface{}, name interface{}, namespace interface{}, all interface{}) *MockClient_GetValues_Call {
	return &MockClient_GetValues_Call{Call: _e.mock.On("GetValues", ctx, name, namespace, all)}
}

func (_c *MockClient_GetValues_Call) Run(run func(ctx context.Context, name string, namespace string, all bool)) *MockClient_GetValues_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 bool
		if args[3] != nil {
			arg3 = args[3].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockClient_GetValues_Call) Return(bytes []byte, err error) *MockClient_GetValues_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockClient_GetValues_Call) RunAndReturn(run func(ctx context.Context, name string, namespace string, all bool) ([]byte, error)) *MockClient_GetValues_Call {
	_c.Call.Return(run)
	return _c
}

// Install provides a mock function for the type MockClient
func (_mock *MockClient) Install(ctx context.Context, name string, namespace string, options helm.UpgradeOptions) error {
	ret := _mock.Called(ctx, name, namespace, options)

	if len(ret) == 0 {
		panic("no return value specified for Install")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, helm.UpgradeOptions) error); ok {
		r0 = returnFunc(ctx, name, namespace, options)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_Install_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Install'
type MockClient_Install_Call struct {
	*mock.Call
}

// Install is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - namespace string
//   - options helm.UpgradeOptions
func (_e *MockClient_Expecter) Install(ctx interface{}, name interface{}, namespace interface{}, options interface{}) *MockClient_Install_Call {
	return &MockClient_Install_Call{Call: _e.mock.On("Install", ctx, name, namespace, options)}
}

func (_c *MockClient_Install_Call) Run(run func(ctx context.Context, name string, namespace string, options helm.UpgradeOptions)) *MockClient_Install_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 helm.UpgradeOptions
		if args[3] != nil {
			arg3 = args[3].(helm.UpgradeOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockClient_Install_Call) Return(err error) *MockClient_Install_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_Install_Call) RunAndReturn(run func(ctx context.Context, name string, namespace string, options helm.UpgradeOptions) error) *MockClient_Install_Call {
	_c.Call.Return(run)
	return _c
}

// Pull provides a mock function for the type MockClient
func (_mock *MockClient) Pull(ctx context.Context, name string, options helm.UpgradeOptions) error {
	ret := _mock.Called(ctx, name, options)

	if len(ret) == 0 {
		panic("no return value specified for Pull")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, helm.UpgradeOptions) error); ok {
		r0 = returnFunc(ctx, name, options)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_Pull_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Pull'
type MockClient_Pull_Call struct {
	*mock.Call
}

// Pull is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - options helm.UpgradeOptions
func (_e *MockClient_Expecter) Pull(ctx interface{}, name interface{}, options interface{}) *MockClient_Pull_Call {
	return &MockClient_Pull_Call{Call: _e.mock.On("Pull", ctx, name, options)}
}

func (_c *MockClient_Pull_Call) Run(run func(ctx context.Context, name string, options helm.UpgradeOptions)) *MockClient_Pull_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 helm.UpgradeOptions
		if args[2] != nil {
			arg2 = args[2].(helm.UpgradeOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockClient_Pull_Call) Return(err error) *MockClient_Pull_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_Pull_Call) RunAndReturn(run func(ctx context.Context, name string, options helm.UpgradeOptions) error) *MockClient_Pull_Call {
	_c.Call.Return(run)
	return _c
}

// Rollback provides a mock function for the type MockClient
func (_mock *MockClient) Rollback(ctx context.Context, name string, namespace string) error {
	ret := _mock.Called(ctx, name, namespace)

	if len(ret) == 0 {
		panic("no return value specified for Rollback")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, name, namespace)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_Rollback_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Rollback'
type MockClient_Rollback_Call struct {
	*mock.Call
}

// Rollback is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - namespace string
func (_e *MockClient_Expecter) Rollback(ctx interface{}, name interface{}, namespace interface{}) *MockClient_Rollback_Call {
	return &MockClient_Rollback_Call{Call: _e.mock.On("Rollback", ctx, name, namespace)}
}

func (_c *MockClient_Rollback_Call) Run(run func(ctx context.Context, name string, namespace string)) *MockClient_Rollback_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockClient_Rollback_Call) Return(err error) *MockClient_Rollback_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_Rollback_Call) RunAndReturn(run func(ctx context.Context, name string, namespace string) error) *MockClient_Rollback_Call {
	_c.Call.Return(run)
	return _c
}

// Status provides a mock function for the type MockClient
func (_mock *MockClient) Status(ctx context.Context, name string, namespace string) ([]byte, error) {
	ret := _mock.Called(ctx, name, namespace)

	if len(ret) == 0 {
		panic("no return value specified for Status")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) ([]byte, error)); ok {
		return returnFunc(ctx, name, namespace)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) []byte); ok {
		r0 = returnFunc(ctx, name, namespace)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, name, namespace)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_Status_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Status'
type MockClient_Status_Call struct {
	*mock.Call
}

// Status is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - namespace string
func (_e *MockClient_Expecter) Status(ctx interface{}, name interface{}, namespace interface{}) *MockClient_Status_Call {
	return &MockClient_Status_Call{Call: _e.mock.On("Status", ctx, name, namespace)}
}

func (_c *MockClient_Status_Call) Run(run func(ctx context.Context, name string, namespace string)) *MockClient_Status_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockClient_Status_Call) Return(bytes []byte, err error) *MockClient_Status_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockClient_Status_Call) RunAndReturn(run func(ctx context.Context, name string, namespace string) ([]byte, error)) *MockClient_Status_Call {
	_c.Call.Return(run)
	return _c
}

// Upgrade provides a mock function for the type MockClient
func (_mock *MockClient) Upgrade(ctx context.Context, name string, namespace string, options helm.UpgradeOptions) error {
	ret := _mock.Called(ctx, name, namespace, options)

	if len(ret) == 0 {
		panic("no return value specified for Upgrade")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, helm.UpgradeOptions) error); ok {
		r0 = returnFunc(ctx, name, namespace, options)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_Upgrade_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upgrade'
type MockClient_Upgrade_Call struct {
	*mock.Call
}

// Upgrade is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - namespace string
//   - options helm.UpgradeOptions
func (_e *MockClient_Expecter) Upgrade(ctx interface{}, name interface{}, namespace interface{}, options interface{}) *MockClient_Upgrade_Call {
	return &MockClient_Upgrade_Call{Call: _e.mock.On("Upgrade", ctx, name, namespace, options)}
}

func (_c *MockClient_Upgrade_Call) Run(run func(ctx context.Context, name string, namespace string, options helm.UpgradeOptions)) *MockClient_Upgrade_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 helm.UpgradeOptions
		if args[3] != nil {
			arg3 = args[3].(helm.UpgradeOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockClient_Upgrade_Call) Return(err error) *MockClient_Upgrade_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_Upgrade_Call) RunAndReturn(run func(ctx context.Context, name string, namespace string, options helm.UpgradeOptions) error) *MockClient_Upgrade_Call {
	_c.Call.Return(run)
	return _c
}
